name: run a python script
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Dependencies
        run: |
          pip install requests 'beautifulsoup4>=4.12.2'
      - name: Run Scraper
        run: python scraper.py
      - name: Git Configure
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Git Add
        run: git add .
      - name: Git Commit & Push
        if: steps.git_add.outcome == 'success'
        run: |
          git commit -m "chore: updated files"
          git push
